<a href="https://colab.research.google.com/github/sndtejaswini0429/student__details/blob/main/stu_info.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
fd = open('record.txt', "r")
txt = fd.read()
fd.close()

In [ ]:
info = txt.split("\n")
info

['1,bob,2nd,cse,60,64,69,70,eligible,app',
 '2,nova,2nd,cse,58,60,65,64,eligibe,ml',
 '3,smrithi,2nd,cse,57,59,70,74,eligible,ai',
 '4,pooja,2nd,cse,45,34,36,37,not eligible,null',
 '5,sushant,2nd,cse,54,43,63,73,eligible,robotics',
 '6,mounika,2nd,cse,55,41,68,58,eligible,ruby',
 '7,mahesh,2nd,cse,25,50,46,37,not eligible,null',
 '8,nihal,2nd,cse,54,69,72,61,eligible,webdevelopment',
 '9,nishitha,2nd,cse,71,59,63,73,eligible,androiddevelopment',
 '10,kiran,2nd,cse,25,20,45,37,noteligible,null',
 '11,rohit,1st,cse,45,34,36,37,noteligible,null',
 '12,mike,1st,cse,45,34,36,37,noteligible,null',
 '13,sushrut,1st,cse,45,21,36,37,noteligible,null',
 '14,ria,1st,cse,58,61,69,65,eligible,app',
 '15,ishan,1st,cse,71,59,68,54,eligible,webdevelopment',
 '16,varun,1st,cse,71,65,63,54,eligible,ruby',
 '17,vindya,1st,cse,45,24,36,37,noteligible,null',
 '18,reshma,1st,cse,45,50,36,58,eligible,ml',
 '19,ravi,1st,cse,45,25,45,37,noteligible,null',
 '20,ekta,1st,cse,45,34,36,37,eligible,ai',
 '21,girish,3rd,cse,45,34,45,41,not eligible,null',
 '22,harini,3rd,cse,14,34,36,37,not eligible,null',
 '23,harsha,3rd,cse,54,34,63,37,eligible,ai',
 '24,hardik,3rd,cse,71,54,36,73,eligible,ml',
 '25,varshini,3rd,cse,65,64,56,70,eligible,ruby',
 '26,swami,3rd,cse,45,21,36,37,not eligible,null',
 '27,seshu,3rd,cse,48,34,30,37,not eligible,null',
 '28,swathi,3rd,cse,70,69,68,70,eligible,androiddevelopment',
 '29,lalitha,3rd,cse,41,50,63,54,eligible,ai',
 '30,kamini,3rd,cse,61,65,60,58,eligible,webdevelopment',
 '31,kumar,4rth,cse,65,71,69,67,eligible,ai',
 '32,jackson,4rth,cse,54,69,68,71,eligible,ml',
 '33,roshan,4rth,cse,54,57,65,69,eligible,ruby',
 '34,anupma,4rth,cse,58,59,61,69,eligible,androiddevelopment',
 '35,ramya,4rth,cse,45,30,36,37,not eligible,null',
 '36,srinu,4rth,cse,58,69,65,56,eligible,ruby',
 '37,bhuvna,4rth,cse,60,69,58,56,eligible,webdevelopment',
 '38,hari,4rth,cse,30,25,36,37,not eligible,null',
 '39,sukumar,4rth,cse,58,63,62,70,eligible,ai',
 '40,kavya,4rth,cse,70,68,69,64,eligible,app']

In [ ]:
info=txt.split()
student=input('enter student id:')
for i in info:
  inf=i.split(',')
  #print(inf)
  if(student==inf[0]):
    print("____________________________STUDENT DETAILS______________________________")
    print("id:",inf[0])
    print("student name:",inf[1])
    print("year:",inf[2])
    print("branch:",inf[3])
    print("______________________________MARKS DETAILS_______________________________")
    print("s1:",inf[4])
    print("s2:",inf[5])
    print("s3:",inf[6])
    print("s4:",inf[7])
    print("total=",int(inf[4])+int(inf[5])+int(inf[6])+int(inf[7]))
    avg=(int(inf[4])+int(inf[5])+int(inf[6])+int(inf[7]))/4
    print("average=",avg)
    if (avg>=85): 
      print("pass")   
      print("The Grade of the student with id "+inf[0] +" is O")
    elif (avg>70 and avg<85):
      print("pass")
      print("The Grade of the student with id "+ inf[0] +" is S")
    elif (avg>60 and avg<=70):
      print("pass")
      print("The Grade of the student with id "+inf[0] +" is A")
    elif (avg> 50 and avg<=60):
      print("pass")
      print("The Grade of the student with id "+inf[0]+ " is B")
    else:
      print("The Grade of the student with id "+inf[0] +" is Fail")

    if (inf[8] == "eligible") :
      print("yes the student is eligible for Honor Degree")
      print("domain :", inf[9])
    else:
      print("no, the student is not eligible for Honor Degree")
      #print("domain:", inf[9])

enter student id:25
____________________________STUDENT DETAILS______________________________
id: 25
student name: varshini
year: 3rd
branch: cse
______________________________MARKS DETAILS_______________________________
s1: 65
s2: 64
s3: 56
s4: 70
total= 255
average= 63.75
pass
The Grade of the student with id 25 is A
yes the student is eligible for Honor Degree
domain : ruby

In [ ]:
fd = open("data.json", 'r')
r = fd.read()
fd.close()

In [ ]:
import json
rec = json.loads(r)
rec

{'stu_details': [{'2ndyear': [{'Branch': 'cse',
     'HonorDegree': 'eligible',
     'HonorDomain': 'app',
     'ID': '1',
     'Name': 'bob',
     'S1': '60',
     'S2': '64',
     'S3': '69',
     'S4': '70',
     'Year': '2nd'},
    {'Branch': 'cse',
     'HonorDegree': 'eligibe',
     'HonorDomain': 'ml',
     'ID': '2',
     'Name': 'nova',
     'S1': '58',
     'S2': '60',
     'S3': '65',
     'S4': '64',
     'Year': '2nd'},
    {'Branch': 'cse',
     'HonorDegree': 'eligible',
     'HonorDomain': 'ai',
     'ID': '3',
     'Name': 'smrithi',
     'S1': '57',
     'S2': '59',
     'S3': '70',
     'S4': '74',
     'Year': '2nd'},
    {'Branch': 'cse',
     'HonorDegree': 'noteligible',
     'HonorDomain': 'null',
     'ID': '4',
     'Name': 'pooja',
     'S1': '45',
     'S2': '34',
     'S3': '36',
     'S4': '37',
     'Year': '2nd'},
    {'Branch': 'cse',
     'HonorDegree': 'eligible',
     'HonorDomain': 'robotics',
     'ID': '5',
     'Name': 'sushant',
     'S1': '54',
     'S2': '43',
     'S3': '63',
     'S4': '73',
     'Year': '2nd'},
    {'Branch': 'cse',
     'HonorDegree': 'eligible',
     'HonorDomain': 'ruby',
     'ID': '6',
     'Name': 'mounika',
     'S1': '55',
     'S2': '41',
     'S3': '68',
     'S4': '58',
     'Year': '2nd'},
    {'Branch': 'cse',
     'HonorDegree': 'noteligible',
     'HonorDomain': 'null',
     'ID': '7',
     'Name': 'mahesh',
     'S1': '25',
     'S2': '50',
     'S3': '46',
     'S4': '37',
     'Year': '2nd'},
    {'Branch': 'cse',
     'HonorDegree': 'eligible',
     'HonorDomain': 'webdevelopment',
     'ID': '8',
     'Name': 'nihal',
     'S1': '54',
     'S2': '69',
     'S3': '72',
     'S4': '61',
     'Year': '2nd'},
    {'Branch': 'cse',
     'HonorDegree': 'eligible',
     'HonorDomain': 'androiddevelopment',
     'ID': '9',
     'Name': 'nishitha',
     'S1': '71',
     'S2': '59',
     'S3': '63',
     'S4': '73',
     'Year': '2nd'},
    {'Branch': 'cse',
     'HonorDegree': 'noteligible',
     'HonorDomain': 'null',
     'ID': '10',
     'Name': 'kiran',
     'S1': '25',
     'S2': '20',
     'S3': '45',
     'S4': '37',
     'Year': '2nd'}]},
  {'1styear': [{'Branch': 'cse',
     'HonorDegree': 'noteligible',
     'HonorDomain': 'null',
     'ID': '11',
     'Name': 'rohit',
     'S1': '45',
     'S2': '34',
     'S3': '36',
     'S4': '37',
     'Year': '1st'},
    {'Branch': 'cse',
     'HonorDegree': 'noteligible',
     'HonorDomain': 'null',
     'ID': '12',
     'Name': 'mike',
     'S1': '45',
     'S2': '34',
     'S3': '36',
     'S4': '37',
     'Year': '1st'},
    {'Branch': 'cse',
     'HonorDegree': 'noteligible',
     'HonorDomain': 'null',
     'ID': '13',
     'Name': 'sushrut',
     'S1': '45',
     'S2': '21',
     'S3': '36',
     'S4': '37',
     'Year': '1st'},
    {'Branch': 'cse',
     'HonorDegree': 'eligible',
     'HonorDomain': 'app',
     'ID': '14',
     'Name': 'ria',
     'S1': '58',
     'S2': '61',
     'S3': '69',
     'S4': '65',
     'Year': '1st'},
    {'Branch': 'cse',
     'HonorDegree': 'eligible',
     'HonorDomain': 'webdevelopment',
     'ID': '15',
     'Name': 'ishan',
     'S1': '71',
     'S2': '59',
     'S3': '68',
     'S4': '54',
     'Year': '1st'},
    {'Branch': 'cse',
     'HonorDegree': 'eligible',
     'HonorDomain': 'ruby',
     'ID': '16',
     'Name': 'varun',
     'S1': '71',
     'S2': '65',
     'S3': '63',
     'S4': '54',
     'Year': '1st'},
    {'Branch': 'cse',
     'HonorDegree': 'noteligible',
     'HonorDomain': 'null',
     'ID': '17',
     'Name': 'vindya',
     'S1': '45',
     'S2': '24',
     'S3': '63',
     'S4': '37',
     'Year': '1st'},
    {'Branch': 'cse',
     'HonorDegree': 'eligible',
     'HonorDomain': 'ml',
     'ID': '18',
     'Name': 'reshma',
     'S1': '45',
     'S2': '50',
     'S3': '36',
     'S4': '58',
     'Year': '1st'},
    {'Branch': 'cse',
     'HonorDegree': 'noteligible',
     'HonorDomain': 'null',
     'ID': '19',
     'Name': 'ravi',
     'S1': '45',
     'S2': '25',
     'S3': '45',
     'S4': '37',
     'Year': '1st'},
    {'Branch': 'cse',
     'HonorDegree': 'eligible',
     'HonorDomain': 'ai',
     'ID': '20',
     'Name': 'ekta',
     'S1': '45',
     'S2': '34',
     'S3': '36',
     'S4': '37',
     'Year': '1st'}]},
  {'3rdyear': [{'Branch': 'cse',
     'HonorDegree': 'noteligible',
     'HonorDomain': 'null',
     'ID': '21',
     'Name': 'girish',
     'S1': '45',
     'S2': '34',
     'S3': '45',
     'S4': '41',
     'Year': '3rd'},
    {'Branch': 'cse',
     'HonorDegree': 'noteligible',
     'HonorDomain': 'null',
     'ID': '22',
     'Name': 'harini',
     'S1': '14',
     'S2': '34',
     'S3': '36',
     'S4': '37',
     'Year': '3rd'},
    {'Branch': 'cse',
     'HonorDegree': 'eligible',
     'HonorDomain': 'ai',
     'ID': '23',
     'Name': 'harsha',
     'S1': '54',
     'S2': '34',
     'S3': '63',
     'S4': '37',
     'Year': '3rd'},
    {'Branch': 'cse',
     'HonorDegree': 'eligible',
     'HonorDomain': 'ml',
     'ID': '24',
     'Name': 'hardik',
     'S1': '71',
     'S2': '54',
     'S3': '36',
     'S4': '73',
     'Year': '3rd'},
    {'Branch': 'cse',
     'HonorDegree': 'eligible',
     'HonorDomain': 'ruby',
     'ID': '25',
     'Name': 'varshini',
     'S1': '65',
     'S2': '64',
     'S3': '56',
     'S4': '70',
     'Year': '3rd'},
    {'Branch': 'cse',
     'HonorDegree': 'noteligible',
     'HonorDomain': 'null',
     'ID': '26',
     'Name': 'swami',
     'S1': '45',
     'S2': '21',
     'S3': '36',
     'S4': '37',
     'Year': '3rd'},
    {'Branch': 'cse',
     'HonorDegree': 'noteligible',
     'HonorDomain': 'null',
     'ID': '27',
     'Name': 'seshu',
     'S1': '48',
     'S2': '34',
     'S3': '30',
     'S4': '37',
     'Year': '3rd'},
    {'Branch': 'cse',
     'HonorDegree': 'eligible',
     'HonorDomain': 'androiddevelopment',
     'ID': '28',
     'Name': 'swathi',
     'S1': '70',
     'S2': '69',
     'S3': '68',
     'S4': '70',
     'Year': '3rd'},
    {'Branch': 'cse',
     'HonorDegree': 'eligible',
     'HonorDomain': 'ai',
     'ID': '29',
     'Name': 'lalitha',
     'S1': '41',
     'S2': '50',
     'S3': '63',
     'S4': '54',
     'Year': '3rd'},
    {'Branch': 'cse',
     'HonorDegree': 'eligible',
     'HonorDomain': 'webdevelopment',
     'ID': '30',
     'Name': 'kamini',
     'S1': '61',
     'S2': '65',
     'S3': '60',
     'S4': '58',
     'Year': '3rd'}]},
  {'4thyear': [{'Branch': 'cse',
     'HonorDegree': 'eligible',
     'HonorDomain': 'ai',
     'ID': '31',
     'Name': 'kumar',
     'S1': '65',
     'S2': '71',
     'S3': '69',
     'S4': '67',
     'Year': '4rth'},
    {'Branch': 'cse',
     'HonorDegree': 'eligible',
     'HonorDomain': 'ruby',
     'ID': '33',
     'Name': 'roshan',
     'S1': '54',
     'S2': '57',
     'S3': '65',
     'S4': '69',
     'Year': '4rth'},
    {'Branch': 'cse',
     'HonorDegree': 'eligible',
     'HonorDomain': 'androiddevelopment',
     'ID': '34',
     'Name': 'anupma',
     'S1': '58',
     'S2': '59',
     'S3': '61',
     'S4': '69',
     'Year': '4rth'},
    {'Branch': 'cse',
     'HonorDegree': 'noteligible',
     'HonorDomain': 'null',
     'ID': '35',
     'Name': 'ramya',
     'S1': '45',
     'S2': '30',
     'S3': '36',
     'S4': '37',
     'Year': '4rth'},
    {'Branch': 'cse',
     'HonorDegree': 'eligible',
     'HonorDomain': 'ruby',
     'ID': '36',
     'Name': 'srinu',
     'S1': '58',
     'S2': '69',
     'S3': '65',
     'S4': '56',
     'Year': '4rth'},
    {'Branch': 'cse',
     'HonorDegree': 'eligible',
     'HonorDomain': 'webdevelopment',
     'ID': '37',
     'Name': 'bhuvna',
     'S1': '60',
     'S2': '69',
     'S3': '58',
     'S4': '56',
     'Year': '4rth'},
    {'Branch': 'cse',
     'HonorDegree': 'noteligible',
     'HonorDomain': 'null',
     'ID': '38',
     'Name': 'hari',
     'S1': '30',
     'S2': '25',
     'S3': '36',
     'S4': '37',
     'Year': '4rth'},
    {'Branch': 'cse',
     'HonorDegree': 'eligible',
     'HonorDomain': 'ai',
     'ID': '39',
     'Name': 'sukumar',
     'S1': '58',
     'S2': '63',
     'S3': '62',
     'S4': '70',
     'Year': '4rth'},
    {'Branch': 'cse',
     'HonorDegree': 'eligible',
     'HonorDomain': 'app',
     'ID': '40',
     'Name': 'kavya',
     'S1': '70',
     'S2': '68',
     'S3': '69',
     'S4': '64',
     'Year': '4rth'}]}]}

In [ ]:
new_id = int(input("Enter student id:"))
new_name = str(input("Enter name: "))
new_hdomain = str(input("enter new domain: "))



rec[inf[0]] = {'name': new_name, "Honordomain": new_hdomain }

js = json.dumps(rec)


fd = open("data.json",'w')
fd.write(js)
fd.close()

Enter student id:25
Enter name: var